# Generated by Django 2.0.6 on 2018-06-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputadoestadual',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeputadoEstadual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deputadofederal',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeputadoFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigo', models.AutoField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('eleitores', models.IntegerField(db_column='Eleitores')),
                ('area', models.IntegerField(db_column='Area')),
                ('populacao', models.IntegerField(db_column='Populacao')),
            ],
            options={
                'db_table': 'Estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Governador',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Governador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.AutoField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('eleitores', models.IntegerField(db_column='Eleitores')),
                ('area', models.IntegerField(db_column='Area')),
                ('população', models.IntegerField(db_column='População')),
            ],
            options={
                'db_table': 'Municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('sigla', models.CharField(db_column='Sigla', max_length=5, primary_key=True, serialize=False)),
                ('filiados', models.IntegerField(db_column='Filiados')),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('posicao', models.TextField(db_column='Posicao')),
                ('logo', models.TextField(db_column='Logo')),
            ],
            options={
                'db_table': 'Partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefeito',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Prefeito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Presidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('numero', models.IntegerField(db_column='Numero', primary_key=True, serialize=False)),
                ('juiz', models.CharField(db_column='Juiz', max_length=45)),
                ('forum', models.CharField(db_column='Forum', max_length=45)),
                ('delito', models.CharField(db_column='Delito', max_length=45)),
            ],
            options={
                'db_table': 'Processos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('numero', models.IntegerField(db_column='Numero', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='Data')),
                ('descrição', models.TextField(db_column='Descrição')),
            ],
            options={
                'db_table': 'Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Senador',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Senador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Vereador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeputadoestadualHasProjetos',
            fields=[
                ('deputadoestadual_cpf', models.ForeignKey(db_column='DeputadoEstadual_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Deputadoestadual')),
            ],
            options={
                'db_table': 'DeputadoEstadual_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeputadofederalHasProjetos',
            fields=[
                ('deputadofederal_cpf', models.ForeignKey(db_column='DeputadoFederal_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Deputadofederal')),
            ],
            options={
                'db_table': 'DeputadoFederal_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GovernadorHasProjetos',
            fields=[
                ('governador_cpf', models.ForeignKey(db_column='Governador_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Governador')),
            ],
            options={
                'db_table': 'Governador_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrefeitoHasProjetos',
            fields=[
                ('prefeito_cpf', models.ForeignKey(db_column='Prefeito_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Prefeito')),
            ],
            options={
                'db_table': 'Prefeito_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresidenteHasProjetos',
            fields=[
                ('presidente_cpf', models.ForeignKey(db_column='Presidente_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Presidente')),
            ],
            options={
                'db_table': 'Presidente_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasDeputadoestadual',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_DeputadoEstadual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasDeputadofederal',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_DeputadoFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasGovernador',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Governador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasPrefeito',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Prefeito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasPresidente',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Presidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasSenador',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Senador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasVereador',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Vereador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SenadorHasProjetos',
            fields=[
                ('senador_cpf', models.ForeignKey(db_column='Senador_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Senador')),
            ],
            options={
                'db_table': 'Senador_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VereadorHasProjetos',
            fields=[
                ('vereador_cpf', models.ForeignKey(db_column='Vereador_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='candidatos.Vereador')),
            ],
            options={
                'db_table': 'Vereador_has_Projetos',
                'managed': False,
            },
        ),
    ]
