# Generated by Django 2.0.6 on 2018-06-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deputadoestadual',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeputadoEstadual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deputadofederal',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DeputadoFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigo', models.AutoField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('eleitores', models.IntegerField(db_column='Eleitores')),
                ('area', models.IntegerField(db_column='Area')),
                ('populacao', models.IntegerField(db_column='Populacao')),
            ],
            options={
                'db_table': 'Estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Governador',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Governador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.AutoField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('eleitores', models.IntegerField(db_column='Eleitores')),
                ('area', models.IntegerField(db_column='Area')),
                ('população', models.IntegerField(db_column='População')),
            ],
            options={
                'db_table': 'Municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('sigla', models.CharField(db_column='Sigla', max_length=5, primary_key=True, serialize=False)),
                ('filiados', models.IntegerField(db_column='Filiados')),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('posicao', models.TextField(db_column='Posicao')),
                ('logo', models.TextField(db_column='Logo')),
            ],
            options={
                'db_table': 'Partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefeito',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Prefeito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Presidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('numero', models.IntegerField(db_column='Numero', primary_key=True, serialize=False)),
                ('juiz', models.CharField(db_column='Juiz', max_length=45)),
                ('forum', models.CharField(db_column='Forum', max_length=45)),
                ('delito', models.CharField(db_column='Delito', max_length=45)),
            ],
            options={
                'db_table': 'Processos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('numero', models.IntegerField(db_column='Numero', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='Data')),
                ('descrição', models.TextField(db_column='Descrição')),
            ],
            options={
                'db_table': 'Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Senador',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Senador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vereador',
            fields=[
                ('nome', models.CharField(db_column='Nome', max_length=25)),
                ('localnasc', models.CharField(db_column='LocalNasc', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=1)),
                ('escolaridade', models.CharField(db_column='Escolaridade', max_length=45)),
                ('cpf', models.IntegerField(db_column='CPF', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Vereador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeputadoestadualHasProjetos',
            fields=[
                ('deputadoestadual_cpf', models.ForeignKey(db_column='DeputadoEstadual_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Deputadoestadual')),
            ],
            options={
                'db_table': 'DeputadoEstadual_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeputadofederalHasProjetos',
            fields=[
                ('deputadofederal_cpf', models.ForeignKey(db_column='DeputadoFederal_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Deputadofederal')),
            ],
            options={
                'db_table': 'DeputadoFederal_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GovernadorHasProjetos',
            fields=[
                ('governador_cpf', models.ForeignKey(db_column='Governador_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Governador')),
            ],
            options={
                'db_table': 'Governador_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrefeitoHasProjetos',
            fields=[
                ('prefeito_cpf', models.ForeignKey(db_column='Prefeito_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Prefeito')),
            ],
            options={
                'db_table': 'Prefeito_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresidenteHasProjetos',
            fields=[
                ('presidente_cpf', models.ForeignKey(db_column='Presidente_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Presidente')),
            ],
            options={
                'db_table': 'Presidente_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasDeputadoestadual',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_DeputadoEstadual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasDeputadofederal',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_DeputadoFederal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasGovernador',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Governador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasPrefeito',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Prefeito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasPresidente',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Presidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasSenador',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Senador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessosHasVereador',
            fields=[
                ('processos_numero', models.ForeignKey(db_column='Processos_Numero', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Processos')),
            ],
            options={
                'db_table': 'Processos_has_Vereador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SenadorHasProjetos',
            fields=[
                ('senador_cpf', models.ForeignKey(db_column='Senador_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Senador')),
            ],
            options={
                'db_table': 'Senador_has_Projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VereadorHasProjetos',
            fields=[
                ('vereador_cpf', models.ForeignKey(db_column='Vereador_CPF', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='deputado_estadual.Vereador')),
            ],
            options={
                'db_table': 'Vereador_has_Projetos',
                'managed': False,
            },
        ),
    ]
